### ISSUE TITLE
L2 topology in Appendix A

### ISSUE THREAD

**Issue by italobusi** [ietf-ccamp-wg/draft-ietf-ccamp-mw-topo-yang#10]
Appendix A assumes to use the L2 topology model defined in [RFC8944](https://datatracker.ietf.org/doc/html/rfc8944)

In ETSI DGS mWT-024. the Ethernet TE and Client Topology topology model defined in [draft-ietf-ccamp-eth-client-te-topo-yang](https://datatracker.ietf.org/doc/html/draft-ietf-ccamp-eth-client-te-topo-yang)

The advantages of the Ethernet TE and Client Topology topology model are that:
- It supports administrative/operational state management from TE topology (profile)
- It supports for inter-domain link discovery (plug-id) from TE topology (profile)
- It supports a common way to manage link bundling (e.g., LAG) from TE topology (profile)
- Allows reporting the VLAN classification capabilities at the edge of the network

**Comment by JonasAhl** [comment]
The meeting agrees with the proposal and assigns the task to Italo to make an update of the JSON example accordingly.

**Comment by JonasAhl** [comment]
Now included in the latest github version.
