### ISSUE TITLE
Contact ccamp chairs about errata 

### ISSUE THREAD

**Issue by samans** [ietf-ccamp-wg/draft-ietf-ccamp-mw-topo-yang#12]
Errata status
  - https://datatracker.ietf.org/doc/html/rfc8561
  - https://www.rfc-editor.org/errata_search.php?rfc=8561&rec_status=0
  - Contact Daniele and Fatai about errate process (Issue)

**Comment by samans** [comment]
The guidance I received is...

A note to the relevant AD from the lead author, with a copy to the CCAMP working group, indicating the author’s expectation about resolution should cause the AD to act.

So...  
Jonas needs to send the email to Fatai Zhang (Document Shephard) and John Scudder (AD) with CC to the current leaders:
Chairs Daniele Ceccarelli Fatai Zhang
AD: John Scudder
CCAMP Secretary:  Oscar de Dios
Responsible AD when draft was completed: Deborah Brungard

**Comment by JonasAhl** [comment]
Errata verified and included in data tracker.
