### ISSUE TITLE
Inconsistencies in the examples

### ISSUE THREAD

**Issue by JonasAhl** [ietf-ccamp-wg/draft-ietf-ccamp-mw-topo-yang#17]
Go through the two examples to remove any inconsistences wrt to the type of configurations and associated frequencies.

**Comment by DanielaSpreafico** [comment]
I found the following inconsistencies on example-fold.json (2+0 case) on  "ietf-interfaces:interfaces" section:

  1.  "interface": [
  ..
  ..
      {
        "name": "RLT-1",
        "description": "'Radio Link Terminal 1'",
        "type": "iana-if-type:microwaveRadioLinkTerminal",
        "ietf-microwave-radio-link:mode":
        "ietf-microwave-types:**one-plus-zero",** --> to be changed to **two-plus-zero**

The same for RLT-2.

2.     The 'tx-frequency' attribute values for CT-2/CT-3/CT-4 need to be changed according to the 'tx-frequency' 
        and 'rx-frequency' attributes of 'te-link-attributes' :
      
         "interface": [
           ...
        "name": "CT-3",
         ...
        "ietf-microwave-radio-link:tx-frequency": **10728000**, --> **10528000**
        ...
        "name": "CT-2",
        ...
        "ietf-microwave-radio-link:tx-frequency": **10728000**, --> **10615000**
        ...
        "name": "CT-4",
        ...
        "ietf-microwave-radio-link:tx-frequency": **10728000**, --> **10415000**

**Comment by DanielaSpreafico** [comment]
These inconsistencies were present on the actual draft.

**Comment by samans** [comment]
The updates were made to the 2+0 json example.
