### ISSUE TITLE
Create SVG versions of the diagrams/pictures in the two examples

### ISSUE THREAD

**Issue by JonasAhl** [ietf-ccamp-wg/draft-ietf-ccamp-mw-topo-yang#19]

**Comment by samans** [comment]
Information about SVG files...

```raw
For svg art-work, do this in the xml code...
        <artset anchor="test">
           <artwork type="svg" src="drawing.svg">
           </artwork>
           <artwork type="ascii-art" align="left" alt=""><![CDATA[
                 ….
           </artwork>
       </artset>
```

Markdown doesn't support the artset
https://www.ietf.org/archive/id/draft-fossati-svg-test-01.html

goat (ascii to svg) can't get this to install.
https://xml2rfc.tools.ietf.org/xml2rfc3.html
https://www.rfc-editor.org/rse/wiki/doku.php?id=svg_files
https://www.rfc-editor.org/materials/FAQ-xml2rfcv3.html#name-how-do-i-generate-svg-that

**Comment by samans** [comment]
Discussion related to diagrams, add new action to fix legend. (a new action item will be created with the list of updates)
Process is to run makefile to generate xml file, then modify xml file to include artset.
goat works but does not provide a good representation of the ascii art we currently have.  So use the hand drawn svg for the svg version.
