### ISSUE TITLE
Example updates

### ISSUE THREAD

**Issue by samans** [ietf-ccamp-wg/draft-ietf-ccamp-mw-topo-yang#27]
Provide updated example in the mw-topo-yang draft that includes the use of if-ref-topo-yang and bwa-topo-yang.  Add the bwa-topo-yang and if-ref-topo-yang as an informative reference.

Put the geolocation data in the node instead of the termination-point.  The te-topology model supports adding the geolocation data to nodes.

**Comment by samans** [comment]
Take the example1plus1.json and example2plus0.json examples from https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-mw-topo-yang/ and remove the interface-reference and bandwidth-availability elements.
Create a generic example for interface-reference and bandwidth-availability for use in their respective drafts.
Maintain a combined example (that includes mw, bwa, and if-ref) that can be used in presentations to show how to use the drafts together.

**Comment by samans** [comment]
Validate all examples

**Comment by samans** [comment]
- Question on the example related to geo-location information associated with the termination-point.  Put the geolocation data in the node instead of the termination-point.  The te-topology model supports adding the geolocation data to nodes.

**Comment by DanielaSpreafico** [comment]
A new example file exampleInterfRef.json has been uploaded on a new branch on [draft-ietf-ccamp-if-ref-topo-yang](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-if-ref-topo-yang) and submitted a pull request for that.

For the new example exampleBwa.json the file has been uploaded directly on the branch Generic-drafts.

For the update of [draft-ietf-ccamp-mw-topo-yang](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-mw-topo-yang)  new files (example1plus1-withoutBwaInterfRef.json  and example2plus0-withoutBwaInterfRef.json ) have been uploaded on the branch Generic-drafts.

Checks are needed for all files.
