### ISSUE TITLE
WG Last call : comments from Tom Petch to be addressed

### ISSUE THREAD

**Issue by DanielaSpreafico** [ietf-ccamp-wg/draft-ietf-ccamp-mw-topo-yang#31]
Here the comments to be addressed:

--
A follow up to an earlier comment of mine relating to
leaf actual-transmitted-level {
type decimal64 {
fraction-digits 1;
range "0..99";
I was unsure if the maximum value was then 99.9 or 99.0 so I asked on the NETMOD list and the answer is 99.0. I note that the same construct is used in RFC8561 so I assume that 99.0 is a magic number in microwave.

--
One more thought. The Appendices would benefit from a reference to RFC8792.

--
8561 is an import so must be a Normative reference

"ETSI EN 302 217-1 -
"ETSI EN 301 129 -
need adding as references as a URL so I can see if they are accessible

1.1
should include
ctp
rlt
rltp
snir
IMHO

carries, in various configurations/modes. T perhaps 'carriers'

. The supporting carriers are identified by its termination points /its/their/

s.3.3
L2 ethernet
Is there an Ethernet that is a different layer?

s.3.4
augmented by the microwave topology model a reference would be useful

module
snir
fraction-digits 1;
range "0..99";
I imagine that that excludes 99.9 or 99.1 etc

actual transmitted level
ditto

when choices specify mw-tp mw-link is one of the choice mandatory?

apply only for networks with an microwave network topology type
/an/a/

A.1
10.10.10.1
is not an address for documentation use

A.2
dirro

B.1
ditto

The authors would like to thank ...

**Comment by DanielaSpreafico** [comment]
I try to reply to the comments received:
 
1. leaf actual-transmitted-level {
type decimal64 {
fraction-digits 1;
range "0..99";
_I was unsure if the maximum value was then 99.9 or 99.0 so I asked on the NETMOD list and the answer is 99.0. I note that the same construct is used in RFC8561 so I assume that 99.0 is a magic number in microwave._ 
**Reply: For the setting of transmitted power (maximum-nominal-power) the range could fit the 99.0 limit. For the value of the measure (actual-transmitted-level) perhaps some values over the 99.0 limit could be used for specific use cases (fail, tx-mute,..) that don’t allow to retrieve the actual value (the same for snir).**

2. _One more thought. The Appendices would benefit from a reference to RFC8792._ 
 **Reply: OK, to add (Normative o Informative ? ):**
[RFC8792]  Watsen, K., Auerswald, E., Farrel,  A., Wu, Qu, "Handling Long Lines in Content of Internet-Drafts and RFCs”, RFC 8792, DOI 10.17487/RFC8792, June 2020, <https://www.rfc-editor.org/rfc/rfc8792>.

3. _8561 is an import so must be a Normative reference_ 
**Reply: OK, to add on 6.1.  section:**
[RFC8561]  Ahlberg, J., Ye, M., Li, X., Spreafico, D., Vaupotic, M., "A YANG Data Model for Microwave radio Link”, RFC 8561, DOI 10.17487/RFC8561, June 2019, <https://www.rfc-editor.org/rfc/rfc8561>.

4. _"ETSI EN 302 217-1 -
"ETSI EN 301 129 -
need adding as references as a URL so I can see if they are accessible_ 
**Reply: 
OK, to add on 6.2 section (Informative):**
**-	For ETSI EN 302 217-1, it is already on RFC 8561:**
[EN302217-1] 
              ETSI, "Fixed Radio Systems; Characteristics and
              requirements for point-to-point equipment and antennas;
              Part 1: Overview, common characteristics and system-
              dependent requirements", EN 302 217-1 V3.1.0, May 2017. 
**A new version exists:**
[EN302217-1] 
              ETSI, "Fixed Radio Systems; Characteristics and requirements 
             for point-to-point equipment and antennas; Part 1: Overview, 
             common characteristics and requirements not related to access 
             to radio spectrum", EN 302 217-1 Vxxx, Oct 2021. 

**-	For ETSI EN 301 129 , it is already on RFC 8561:**
  [EN301129] ETSI, "Transmission and Multiplexing (TM); Digital Radio
              Relay Systems (DRRS); Synchronous Digital Hierarchy (SDH);
              System performance monitoring parameters of SDH DRRS", EN
              301 129 V1.1.2, May 1999.

5.  _1.1
should include_
_ctp_ **Reply:  OK to add (in the acronyms list) :  CTP:		Carrier Termination Point**
_rlt_ **Reply:  OK to add  (in the acronyms list) :   RLT:		Radio Link terminal**
_rltp_ **Reply:  OK to add  (in the acronyms list) : RLTP:	Radio Link Termination Point**
_snir_ **Reply:  OK to add  (in the acronyms list) : SNIR:	Signal Noise Interference Ratio**
_IMHO_ **Reply:  ???**

6. _carries, in various configurations/modes. T perhaps 'carriers'_ 
**Reply:  OK,  ‘carries’  to 'carriers' on 3.2 section**

7.  _. The supporting carriers are identified by its termination points /its/their/_ 
**Reply:  OK,  ‘its’ to ‘their’ on 3.2**

8. _s.3.3a
L2 ethernet
Is there an Ethernet that is a different layer?_ 
**Reply:  YES, the L1 ethernet is another ethernet layer. No change.**

9. _s.3.4
augmented by the microwave topology model a reference would be useful_ 
**Reply:  reference to Traffic   Engineering (TE) Topologies or to microwave topology ?**

10. _module
snir
fraction-digits 1;
range "0..99";
I imagine that that excludes 99.9 or 99.1 etc_ 
**Reply:  see previous reply at the point 1.**

11. _actual transmitted level 
ditto_
**Reply:  see previous reply at the begin.**

12. _when choices specify mw-tp mw-link is one of the choice mandatory?_ 
**Reply:  ??**

13. _apply only for networks with an microwave network topology type
/an/a/_ 
**Reply:  OK, to change ‘an’ to ‘a’.**

14. _A.1
10.10.10.1
is not an address for documentation use_
**Reply: Which address can be used?**

15. _A.2
dirro_

15. _B.1
ditto_

16. _The authors would like to thank ..._ 
**Reply: I think thanks to Scott, correct? Others?**

**Comment by samans** [comment]
1.       leaf actual-transmitted-level {
          type decimal64 {
            fraction-digits 1;
            range "0..99"; <--- delete this
          }
          units "dBm";
          config false;  
2. see above {{!RFC8792}}
3. {{RFC8561}}
4. check ietf xml database for the references to ETSI EN 302 217-1 - ETSI EN 301 129 or create by hand in the draft.  Ask how to get the xml file included in the database.
5. add abbreviations
6. typo
7. typo
8. reply back with reason for no change
9. The microwave topology model is the model being defined by this ID.  So no reference is needed.  Maybe change the wording to "augmented by THIS microwave topology model"
10. Remove range same as point 1.
11. See point 1 and 10
12. Review each choice statement and determine if we want to make them mandatory:  See    The "mandatory" statement, which is optional, takes as an argument
   the string "true" or "false" and puts a constraint on valid data.  If
   "mandatory" is "true", at least one node from exactly one of the
   choice's case branches MUST exist.
13. typo
14. https://www.rfc-editor.org/rfc/rfc3330.txt use 192.0.2.1 & 192.0.2.2 or whatever
15. issue 14
16. issue 14
17. Thanks section. Ask the normal contributors to this call if they want to be listed.

**Comment by samans** [comment]
Issues resolved and included in version -08.
