### ISSUE TITLE
•	Request & consider feedback from CCAMP on the suggestion to include generic modules for bandwidth & interface ref 

### ISSUE THREAD

**Issue by JonasAhl** [ietf-ccamp-wg/draft-ietf-ccamp-mw-topo-yang#5]

**Comment by samans** [comment]
Suggestion is to point out that YANG model has been decomposed into generic portion and mw portion.  Get feedback on the decomposition when draft is reviewed by the YANG doctors.

**Comment by samans** [comment]
Based on CCAMP comments and consensus the internet draft has been split into three internet drafts one for each yang module.  There is a mw-topo, bwa, and if-ref internet drafts now.
