### ISSUE TITLE
Consider including more example instantiations (JSON) 

### ISSUE THREAD

**Issue by JonasAhl** [ietf-ccamp-wg/draft-ietf-ccamp-mw-topo-yang#6]
Agree on what examples to include

**Comment by JonasAhl** [comment]
Same as the existing example but with 1+1 configuration of the carriers. Daniela to make a proposal.

**Comment by DanielaSpreafico** [comment]
I add an example (exampleL2OnePlusOne.json) in the repository. 
This is related to 'l2-topology' network type, but a new one could be created for 'ETH topology' type.

**Comment by samans** [comment]
Action to validate the json using yanglint.

**Comment by DanielaSpreafico** [comment]
I updated the json example (file 'exampleL2OnePlusOne.json') to introduce ACM coding modulation mode with 2 modulation values and adding entries on 'link-availability' list.

**Comment by DanielaSpreafico** [comment]
I changed on exampleL2OnePlusOne.jsin file the 'ietf-bandwidth-availability-topology:link-availability' list putting the lowest value of "link-bandwidth" on higher values of "availability".
That both for 'microwave-rltp' and 'microwave-ctp'.
That means the "link-bandwidth" for lower modulation values have more chances of 'availabiliy'.

**Comment by JonasAhl** [comment]
Inserted in the draft.
