### ISSUE TITLE
Send the draft for review by the YANG doctors

### ISSUE THREAD

**Issue by JonasAhl** [ietf-ccamp-wg/draft-ietf-ccamp-mw-topo-yang#7]

**Comment by samans** [comment]
When do we want to send it?  
Deadline for meeting consideration:
2022-03-07 (Monday): Internet Draft submission cut-off (for all drafts, including -00) by UTC 23:59. Upload using the ID Submission Tool.

**Comment by JonasAhl** [comment]
Updated draft ready for review by YANG doctors by 1st week of February

**Comment by samans** [comment]
Implemented the split of the draft into multiple drafts that have one module per draft.
